# Basic set up for three package managers
version: 2
updates:
  # Maintain dependencies for NPM
  - package-ecosystem: "npm"
    directory: "./"
    reviewers:
      - "KostLinux"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: '[NPM Packages]'
      include: scope